/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_plugin_PlatformNatives */

#ifndef _Included_org_swdc_plugin_PlatformNatives
#define _Included_org_swdc_plugin_PlatformNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_plugin_PlatformNatives
 * Method:    addWindowsIcon
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_swdc_plugin_PlatformNatives_addWindowsIcon
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
